export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODCUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODCUCT_LIST_FAILURE';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODCUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODCUCT_DETAILS_FAILURE';
